---
- hosts: masters
  remote_user: ubuntu
  become: yes
  vars:
    secret_name: "{{ secret_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    namespace: "{{ k8s_namespace| default('monitoring') }}"
  tasks:
    - name: Create new secret
      shell: |
            kubectl create secret generic {{ secret_name }} --from-literal=accessKey={{ aws_access_key }}  --from-literal=secretKey={{ aws_secret_key }}  -n {{ namespace }}