---
- hosts: masters
  remote_user: ubuntu
  gather_facts: no
  become: yes
  vars:
    secret_name: "{{ secret_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    namespace: "{{ k8s_namespace| default('monitoring') }}"
  tasks:
    - name: Create TimeStream Secret for Prometheus
      kubernetes.core.k8s:
        state: present
        definition: 
          apiVersion: v1
          kind: Secret
          type: Opaque             
          metadata:
            name: "{{ secret_name }}"
            namespace: "{{ namespace | lower }}"     
          data:
             accessKey: "{{ aws_access_key | b64encode }}"
             secretKey: "{{ aws_secret_key | b64encode }}"