---
- hosts: localhost
  gather_facts: no
  vars:
    region: us-east-1
    masters: 1
    workers: 1
    instance_type: t2.2xlarge

  tasks:
  - fail: msg="cluster_name is required"
    when: cluster_name is undefined

  - name: Get public IP address of the host of Ansible engine
    shell: curl ifconfig.me
    register: my_public_ip

  - name: Create security group
    amazon.aws.ec2_group:
      name: ec2nodes
      description: Used for Ansible automation
      region: "{{ region }}"
      rules:
        - proto: tcp
          ports: 22
          cidr_ip: "{{ my_public_ip.stdout }}/32"
        - proto: tcp
          ports: 6443
          cidr_ip: "0.0.0.0/0"
        - proto: -1
          ports: -1
          group_name: ec2nodes
    diff: false

  - name: Create EC2 instances
    include_role: name=ec2instances
    vars:
      verb: create
      count: "{{ masters | int + workers | int }}"

  - name: Show instance data
    debug:
      msg:
      - "{{ ec2_instances }}"
      - "{{ public_ips }}"
      - "{{ private_ips }}"

  - name: Create a directory to persist data
    ansible.builtin.file:
      path: .data
      state: directory
      mode: '0755'

  - name: Persist instance data
    ansible.builtin.copy:
      content: "{{ ec2_instances | to_nice_json }}"
      dest: ".data/ec2_instances_{{ cluster_name }}.json"

  - name: Assign IPs for k8s masters and workers
    split_ips:
      cluster_name: "{{ cluster_name }}"
      public_ips: "{{ public_ips }}"
      position: "{{ masters | int }}"
    register: split
  - debug:
      var: split
