#  Remove a worker node
- hosts: masters
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  vars:
    node_name_list: [ip-172-31-34-147, ip-172-31-44-50]
  roles:
    - kubernetes/commons/delete-node


- hosts: remove_workers
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - kubernetes/commons/uninstall
