
# Install required packages to Ansible Control Node
- hosts: localhost
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Add Required Packages to Ansible Control Node
      shell: |
             ansible-galaxy collection install cloud.common
             ansible-galaxy collection install kubernetes.core


# Install required packages to the mockcluster node
- hosts: masters
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Add Required Packages to Ansible Control Node
      shell: |
             apt install python3-pip -y
             /usr/bin/python3 -m pip install kubernetes


# Initialize mock environment
- hosts: masters
  remote_user: ubuntu
  become: yes
  vars:
    join_command: "{{lookup('file', '/tmp/mockcluster_join_command') }}"
  tasks:
    - name: Set variables
      set_fact:
        values: "{{ join_command.split(' ')}}"

    - name: Initialize mock environment
      shell: "~/cymba/cmd/mock/init-testbed.sh join {{ values[6] }} {{ values[7] }} {{ values[8] }} {{ values[9] }}"


- hosts: localhost
  become: yes
  tasks:
    - name: Delete local file with token to register managed clusters
      ansible.builtin.file:
        path: /tmp/mockcluster_join_command
        state: absent


# Start mocked clusters
- hosts: masters
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Start mocked clusters
      kubernetes.core.k8s:
        state: present
        src: ~/cymba/cmd/mock/mockclusters.yaml
