## Get the token for joining the worker nodes - copy to Ansible control node
- hosts: masters
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  connection: ssh
  roles:
    - kubernetes/commons/join-token


## Join Worker Nodes to Kubernetes Cluster
- hosts: add_workers
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - kubernetes/commons/install
    - kubernetes/worker


## Delete token for joining the worker nodes from Ansible control node
- hosts: localhost
  become: yes
  tasks:
    - name: Remove worker join-token file from Ansible control node
      ansible.builtin.file:
        path: /tmp/kubernetes_join_command
        state: absent