---
- hosts: localhost
  tasks:
  - name: Read instance data
    include_vars:
      file: .data/ec2_instances.json
      name: ec2_instances

  - name: Delete all instances
    include_role:
      name: ec2instances
    vars:
      verb: delete
      instance_ids: "{{ ec2_instances.instance_ids }}"

  - name: Purge instance data
    ansible.builtin.file:
      path: .data/ec2_instances.json
      state: absent

  post_tasks:
  - debug:
      msg:
      - "{{ ec2_instances }}"
