---
- hosts: masters
  remote_user: ubuntu
  become: true
  gather_facts: yes
  connection: ssh
  tasks:
    - name: Install make
      shell: |
        apt install -y make

    - name: Install helm
      shell : |
        curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
        tar -xzf helm-v3.8.0-linux-amd64.tar.gz
        rm helm-v3.8.0-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/
        rm -r linux-amd64/

    - name: Install jq
      shell: |
        apt install -y jq

    - name: Install clusteradm
      shell: |
        curl -LO https://github.com/open-cluster-management-io/clusteradm/releases/download/v0.1.0/clusteradm_linux_amd64.tar.gz
        tar -xzf clusteradm_linux_amd64.tar.gz
        rm clusteradm_linux_amd64.tar.gz
        mv clusteradm /usr/local/bin/
        rm LICENSE

    - name: Get kealm code
      shell: |
        git -C /root/ clone https://github.com/pdettori/kealm.git

    - name: Get cymba code
      shell: |
        git -C /root/ clone https://github.com/pdettori/cymba.git

    - name: Add kealm's plugin
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "export PATH=$PATH:/root/kealm/deploy"

    - name: Let kc = kubectl
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "alias kc='kubectl'"
