---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Read instance data
    include_vars:
      file: .data/ec2_instances.json
      name: ec2_instances

  - include_role:
      name: ec2instance_data
    vars:
      operation: ips2ids
