---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Include vars
    include_vars:
      file: .ec2instances/ec2_instances.json # persisted instance data
      name: ec2_instances

  - name: Get public IPs
    set_fact:
      public_ips: "{{ ec2_instances | community.general.json_query('instances[*].public_ip') }}"
  - debug:
      var: public_ips

  - name: Get private IPs
    set_fact:
      private_ips: "{{ ec2_instances | community.general.json_query('instances[*].private_ip') }}"
  - debug:
      var: private_ips

  - name: Split public IPs for masters and workers
    split_ips:
      public_ips: "{{ public_ips }}"
      position: 1
    register: split
  - debug:
      var: split
