FROM ubuntu:latest
RUN mkdir -p /tls
RUN mkdir -p /kube
COPY hack/pki/ca/ca.crt /tls/ca.crt
COPY hack/pki/ca/private/ca.key /tls/ca.key
COPY hack/pki/ca/issued/server.crt /tls/server.crt
COPY hack/pki/ca/private/server.key /tls/server.key
COPY kube.conf /kube/kube.conf
VOLUME ["/tls"]
VOLUME ["/kube"]