FROM ubuntu:latest
RUN mkdir -p /tls
RUN mkdir -p /kube
ARG MYENV
COPY hack/kcp/envs/$MYENV/kyst-system/pki/device-config/ca.crt /tls/ca.crt
COPY hack/kcp/envs/$MYENV/kyst-system/pki/device-config/private/ca.key /tls/ca.key
COPY inventory-kubeconfig.yaml /kube/kube.conf
VOLUME ["/tls"]
VOLUME ["/kube"]
CMD ["sleep", "infinity"]
