---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
    region: 'us-east-2'
    cluster_name: 'test-demo-cloud'
    task_revision: 1
  tasks:
    - include_vars: "../.data/{{ region }}_{{ cluster_name }}_agent_helper_vars.yaml"

    - name: Set ECS service task = 0
      community.aws.ecs_service:
        state: present
        region: "{{ region }}"
        name: "{{ task_name }}-service"
        cluster:  "{{ cluster_name }}"
        task_definition: "{{ task_name }}"
        desired_count: 0
            
    - name: Get the list of any remaning running tasks
      shell: aws ecs list-tasks --cluster {{ cluster_name }}
      register: task_list_output

    - name: Store the list of Managed Clusters
      set_fact:
        clusters: "{{ task_list_output.stdout}}"

    - name: Stop a task
      community.aws.ecs_task:
        operation: stop
        cluster: "{{ cluster_name }}"
        task_definition: "{{ task_name }}"
        task: "{{ item }}"
      with_items: '{{ clusters.taskArns }}'

    - name: Delete task definition
      community.aws.ecs_taskdefinition:
        family: "{{ task_name }}"
        revision: "{{ task_revision }}"
        state: absent

    - name: Delete Service
      community.aws.ecs_service:
        name: "{{ task_name }}-service"
        cluster: "{{ cluster_name }}"
        state: absent

    - name: Cluster deletion
      community.aws.ecs_cluster:
        name: "{{ cluster_name }}"
        state: absent

    - name: Remove file deletion_helper_vars.yaml
      ansible.builtin.file:
        path: "../.data/{{ region }}_{{ cluster_name }}_agent_helper_vars.yaml"
        state: absent