---
- hosts: localhost
  gather_facts: no
  vars:
    aws_region_ecr: us-east-1
    aws_region_dynamodb: us-west-2
  tasks:

  - name: Delete the credentials repository from ECR
    shell: |
      aws ecr delete-repository --region {{ aws_region_ecr }} --repository-name limani/credentials --force
