---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
    region: 'us-east-2'
    task_revision: 1
    #cluster_name: "agent-demo-cloud"
  tasks:
    #- include_vars: "{{ region }}_device_helper_vars.yaml"
    - include_vars: "{{ region }}_deletion_helper_vars.yaml"

    - name: Set ECS service task = 0
      community.aws.ecs_service:
        state: present
        region: "{{ region }}"
        name: "{{ task_name }}-braulio-second"
        cluster:  "{{ cluster_name }}"
        task_definition: "{{ task_name }}"
        desired_count: 0
            
    - name: Get the list of any remaning running tasks
      shell: aws ecs list-tasks --cluster {{ cluster_name }}
      register: task_list_output

    - name: Store the list of Managed Clusters
      set_fact:
        clusters: "{{ task_list_output.stdout}}"

    - name: Stop a task
      community.aws.ecs_task:
        operation: stop
        cluster: "{{ cluster_name }}"
        task_definition: "{{ task_name }}"
        task: "{{ item }}"
      with_items: '{{ clusters.taskArns }}'

    - name: Delete task definition
      community.aws.ecs_taskdefinition:
        family: "{{ task_name }}"
        revision: "{{ task_revision }}"
        state: absent

    - name: Delete Service
      community.aws.ecs_service:
        name: "{{ task_name }}-braulio-second"
        cluster: "{{ cluster_name }}"
        state: absent

    - name: Cluster deletion
      community.aws.ecs_cluster:
        name: "{{ cluster_name }}"
        state: absent

 #################################################   
    - name: Delete NAT Gateway and release EIP
      amazon.aws.ec2_vpc_nat_gateway:
        state: 'absent'
        subnet_id: "{{ public_subnet_id }}"
        nat_gateway_id: "{{ nat_id }}"
        release_eip: true
        wait: yes
        wait_timeout: 300

    - name: Delete Internet Gateway for VPC
      amazon.aws.ec2_vpc_igw:
        state: 'absent'
        vpc_id: "{{ vpc_id }}"

    - name: delete route table
      community.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        route_table_id: "{{ item }}"
        lookup: id
        state: 'absent'
      with_items: '{{ route_table_list }}'

    - name: Delete VPC subnets
      amazon.aws.ec2_vpc_subnet:
        state: 'absent'
        vpc_id: "{{ vpc_id }}"
        cidr: "{{ item }}"
      with_items: '{{ cidr_list }}'

    - name: Delete group by its id
      amazon.aws.ec2_group:
        region: "{{ region }}"
        group_id: "{{ sg_id }}"
        state: absent

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        state: 'absent'
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        cidr_block: "{{ vpc_cidr_block }}"

    - name: Remove file deletion_helper_vars.yaml
      ansible.builtin.file:
        path: "{{ region }}_device_helper_vars.yaml"
        state: absent