---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
    accelerator_name: "{{ accelerator_name }}"
    port_num: "{{ port_num }}"
  tasks:
    #- include_vars: "{{ region }}_device_helper_vars.yaml"
    - name: Create AWS Global Accelerator
      shell: aws globalaccelerator create-accelerator --name {{ accelerator_name }} --region us-west-2 
      register: glt_output

    - name: Set Global Accelerator Creation Facts
      set_fact:
        glt_accelerator: "{{ glt_output.stdout }}"

    - name: Debug Global Accelerator Creation
      ansible.builtin.debug:
        msg: "{{ glt_accelerator}}"


    - name: Create AWS Global Accelerator Listener
      shell: |
            aws --region us-west-2  globalaccelerator create-listener \
              --accelerator-arn {{ glt_accelerator.Accelerator.AcceleratorArn }} \
              --port-ranges FromPort={{ port_num }},ToPort={{ port_num }} \
              --protocol TCP 
      register: glt_listiner_output


    - name: Set Global Accelerator Listener Facts
      set_fact:
        glt_listener: "{{ glt_listiner_output.stdout}}"

    - name: Debug Global Accelerator Listener
      ansible.builtin.debug:
        msg: "{{ glt_listener }}"

    - name: Create vars file to help with deletion of AWS Global Accelerator
      ansible.builtin.copy:
        content: "accelerator_arn: '{{ glt_accelerator.Accelerator.AcceleratorArn }}'\nlistener_arn: '{{ glt_listener.Listener.ListenerArn }}'"
        dest: "../.data/global_accelerator_vars.yaml"