---
- hosts: localhost
  gather_facts: no
  vars:
    region: "us-east-2"
    cluster_name: "test-demo-cloud"
    task_name: "test-tasks"
    container_name: nginx
    container_image: "nginx"
    num_replicas: 1
  tasks:
    - include_vars: "../.data/{{ region }}_vpc_helper_vars.yaml"

    - name: Create a log group
      community.aws.cloudwatchlogs_log_group:
        log_group_name: "{{ task_name }}"

    - name: Cluster creation
      community.aws.ecs_cluster:
        name: "{{ cluster_name }}"
        state: present
        region: "{{ region }}"

    - name: Create task definition
      community.aws.ecs_taskdefinition:
        family: "{{ task_name }}"
        containers:
        - name: "{{ container_name }}"
          essential: true
          image: "{{ container_image }}" 
          cpu: 256
          memoryReservation: 512
          logConfiguration:
            logDriver: awslogs
            options:
              awslogs-group: "{{ task_name }}"
              awslogs-region: "{{ region }}"
              awslogs-stream-prefix: ecs
        launch_type: FARGATE
        cpu: "256"
        memory: "512"
        state: present
        network_mode: awsvpc
        execution_role_arn: ecsTaskExecutionRole
      register: task_definition_output

    - name: Debug Task Definition
      ansible.builtin.debug:
        msg: "{{ task_definition_output }}"

    # Basic provisioning example
    - name: Provisioning ECS Service
      community.aws.ecs_service:
        state: present
        region: "{{ region }}"
        name: "{{ task_name }}-service"
        cluster:  "{{ cluster_name }}"
        task_definition: "{{ task_name }}"
        desired_count: "{{ num_replicas }}"
        launch_type: FARGATE
        network_configuration:
          assign_public_ip: no
          subnets:
          - "{{ private_subnet_id }}"
      register: ecs_service_output

    - name: Debug ECS Service
      ansible.builtin.debug:
        msg: "{{ ecs_service_output }}"

    - name: Create vars file to help with deletion of resources
      ansible.builtin.copy:
        content: "cluster_name: {{ cluster_name }}\ntask_name: {{ task_name }}\ncontainerName: {{ container_name }}"
        dest: "../.data/{{ region }}_{{ cluster_name }}_agent_helper_vars.yaml"