---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
    endpoint_region: "us-east-2"
    accelerator_name: "LimaniAccelerator"
    weight: 100
  tasks:
    - include_vars: "{{ region }}_device_helper_vars.yaml"
    
    - name: Create AWS Global Accelerator
      shell: aws globalaccelerator create-accelerator --name {{ accelerator_name }} --region us-west-2 
      register: glt_output

    - name: Set Global Accelerator Creation Facts
      set_fact:
        glt_accelerator: "{{ glt_output.stdout }}"

    - name: Debug Global Accelerator Creation
      ansible.builtin.debug:
        msg: "{{ glt_accelerator}}"


    - name: Create AWS Global Accelerator Listener
      shell: |
            aws --region us-west-2  globalaccelerator create-listener \
              --accelerator-arn {{ glt_accelerator.Accelerator.AcceleratorArn }} \
              --port-ranges FromPort=80,ToPort=80 \
              --protocol TCP 
      register: glt_listiner_output


    - name: Set Global Accelerator Listener Facts
      set_fact:
        glt_listener: "{{ glt_listiner_output.stdout}}"

    - name: Debug Global Accelerator Listener
      ansible.builtin.debug:
        msg: "{{ glt_listener }}"


    - name: Create AWS Global Accelerator Endpoint Group
      shell: |
            aws --region us-west-2 globalaccelerator create-endpoint-group \
                --listener-arn {{ glt_listener.Listener.ListenerArn }} \
                --endpoint-group-region {{ endpoint_region }} \
                --endpoint-configurations EndpointId={{ endpoint_arn }},Weight={{ weight }}
      register: glt_endpoint_output

    - name: Set Accelerator Endpoint Group Facts
      set_fact:
        glt_endpointGroup: "{{ glt_endpoint_output.stdout}}"

    - name: Debug Accelerator Endpoint Group
      ansible.builtin.debug:
        msg: "{{ glt_endpointGroup }}"

    - name: Create vars file to help with deletion of AWS Global Accelerator
      ansible.builtin.copy:
        content: "accelerator_arn: '{{ glt_accelerator.Accelerator.AcceleratorArn }}'\nlistener_arn: '{{ glt_listener.Listener.ListenerArn }}'\nendpoint_group_arn: '{{ glt_endpointGroup.EndpointGroup.EndpointGroupArn }}'"
        dest: "global_accelerator_vars.yaml"