- hosts: masters
  remote_user: ubuntu
  become: yes
  gather_facts: no
  connection: ssh
  vars:
    aws_region_dynamodb: us-west-2

  tasks:
    - include_role: name=deviceserver

    - name: Setup monitoring
      include_role: name=monitoring
