# Scaling the number of clusters
- hosts: masters
  remote_user: ubuntu
  become: yes
  vars:
    nginx_svc: "{{lookup('file', '') }}"
  tasks:
    - name: Deploy Nginx workload
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/controllers/nginx-deployment.yaml

    # - name: Copy using inline content
    #   ansible.builtin.copy:
    #     content: "nginx_svc.yaml"
    #     dest: "/tmp/nginx_svc.yaml"
    #     mode: 0777

    - name: Deploy Nginx Service
      become: yes
      shell: kubectl apply -f {{ nginx_svc }}