---
# tasks file for master
- name: Get public IP address of the node, which is used for extra Subject Alternative Names to use for the API Server serving certificate
  shell: curl ifconfig.me
  register: node_public_ip

- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-cert-extra-sans={{ node_public_ip.stdout }}
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root

- name: Configure master node to accept pods workloads
  become: yes
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: singleNode | bool

- name: install Pod network
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
  args:
    chdir: $HOME

- name: Copy install PV provisioner yaml file
  become: yes
  copy:
    src: "{{ role_path }}/files/local-path-storage.yaml"
    dest: /tmp/local-path-storage.yaml 

- name: install PV provisioner
  become: yes
  shell: |
         kubectl apply -f /tmp/local-path-storage.yaml
         kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  args:
    chdir: $HOME




