---
# tasks file for master
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root

- name: install Pod network
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
  args:
    chdir: $HOME

- name: Copy install PV provisioner yaml file
  become: yes
  copy:
    src: "{{ role_path }}/files/local-path-storage.yaml"
    dest: /tmp/local-path-storage.yaml 


- name: install PV provisioner
  become: yes
  shell: |
         kubectl apply -f /tmp/local-path-storage.yaml
         kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  args:
    chdir: $HOME




