---
# tasks file for cluster-scale
- name: Scaling the number of clusters
  kubernetes.core.k8s_scale:
    api_version: apps/v1
    kind: statefulsets
    name: mockcluster
    namespace: open-cluster-management-agent
    replicas: '{{ num_replicas }}'