- hosts: masters
  remote_user: ubuntu
  become: yes
  gather_facts: no
  connection: ssh
  vars:
    aws_region: "{{ region }}"
    http_nodeport: "{{ http_nodeport }}"
    https_nodeport: "{{ https_nodeport }}"
    myenv: "{{ myenv }}"
    namespace: "{{ namespace }}"
    img_registry: "{{ img_registry }}"
    img_registry_pswd: "{{ img_registry_pswd }}"
    ingress: yes
    num_shards: "{{ num_shards }}"
  tasks:
    - include_role: name=backend

    - name: Setup monitoring
      include_role: name=monitoring